### PR TITLE
Template Support for JS Backend/Target

### PR DESCRIPTION
**Pull request by honewatson**
Removed `import os`.

The macro `tmplf` does not compile in the JS backend due to the use of `readFile`.

Moved main templates.nim declarations into the template folder and moved
the macro `tmplf` into its own file.

The new templates.nim just imports/exports from the templates folder.  templates.nim conditionally imports exports `tmplf` if js is not defined.

`tmplf` is not imported/exported for the JS backend/target but is
imported/exported for all others.

Added test for js target.

### CODE REVIEW

**Comment by onionhammer** [comment]
@honewatson Thanks!

I would prefer if you just put the `tmplf` proc inside a `when` block, rather than breaking things out into separate modules. This would cause far less code flux I think

**Comment by honewatson** [comment]
@onionhammer do you mean in the original templates.nim file in the root of the project?

```nim
proc parse_template(node: NimNode, value: string) =
    ## Parses through entire template, outputing valid
    ## Nim code into the input `node` AST.
    var index = 0
    while index < value.len and
          parse_until_symbol(node, value, index): discard

when defined(js):
    macro tmplf*(body: expr): stmt =
        result = newStmtList()
        result.add parseExpr("result = \"\"")
        var value = readFile(body.strVal)
        parse_template(result, reindent(value))
    
```


 Unfortunately that does not compile when I do that.  The compiler still picks up the identifier.

`templates.nim(321, 21) Error: undeclared identifier: 'readFile'`

**Comment by honewatson** [comment]
@onionhammer ok I have reverted  and put the `tmplf` proc in a `when` block.   The tests still pass along with JS target.

**Comment by onionhammer** [comment]
Relates to #7

**Pull request merged**
